### ISSUE TITLE
Can't build on ARM due to bug in srsLTE 18.09 when SIMD is unavailable

### ISSUE THREAD

**Issue by DrDeke** [falkenber9/falcon#14]
Greetings,

I was trying to build falcon in Ubuntu on ARM, but am unable to do so. I think this is because of a bug ([#265](https://github.com/srsran/srsRAN_4G/issues/265)) in the patched version of srsLTE that the falcon cmake scripts download and compile. 

First, I changed the DISABLE_SIMD option in falcon's CMakeLists.txt from OFF to ON, then proceeded to try to build falcon following the instructions. The cmake step completes without errors, but make fails with: 

```/home/localadm/falcon/build/srsLTE-src/lib/src/phy/fec/turbodecoder.c: In function ‘srslte_tdec_init_manual’:
/home/localadm/falcon/build/srsLTE-src/lib/src/phy/fec/turbodecoder.c:170:22: error: ‘sse16_win_impl’ undeclared (first use in this function)
  170 |       h->dec16[0] = &sse16_win_impl;
```

According to the srsLTE/srsRAN_4G bug I linked above, srsLTE 18.09 does not build correctly when SIMD instructions are unavailable. The recommendation in that thread is to either use srsLTE 18.06 or to wait for the next release after 18.09 (which I believe ended up being 18.12). 

Would it be possible to update falcon to build and run against a version of srsLTE 18.06 or 18.12 with your patches applied to it? Or to provide diffs of your patches to 18.09 so I can attempt to patch one of these versions myself?

Thanks in advance, and thanks for all your work on this software!
